pool: MyAgentsPool

pr:
  branches:
    include:
      - '*'

trigger: none

steps:
- script: echo Hello, world!!!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    echo 'Java home'
    echo $JAVA_HOME
  displayName: 'JAVA_HOME'

- script: |
    echo 'PATH'
    echo $PATH
  displayName: 'PATH'

- script: |
    echo 'WHOAMI'
    whoami
  displayName: 'WHOAMI'

- script: |
    echo $JAVA_HOME_11_X64
  displayName: 'JAVA_HOME_11_X64'