pool: Java-self

pr:
  branches:
    include:
      - '*'

trigger: none

steps:
- script: ls -la
  displayName: dir

# - task: Gradle@2
#   timeoutInMinutes: 4
#   inputs:
#     gradleWrapperFile: 'gradlew'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: 'default'
#     tasks: 'build'
