pool: Java-self

pr:
  branches:
    include:
      - '*'

trigger: none

steps:
- task: Gradle@2
  timeoutInMinutes: 4
  inputs:
    options: --debug
    gradleWrapperFile: 'gradlew'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    tasks: 'build'
