pool: Java-self

pr:
  branches:
    include:
      - '*'

trigger: none

steps:
  - template: pipeline/java/gradle/build-and-test.yml
    parameters:
      testSteps:
        test: 'Unit tests'
        integrationTest: 'Integration tests'
