pool: Java-self

pr:
  branches:
    include:
      - '*'

trigger: none

steps:
- script: echo Hello, world!!!
  displayName: 'Run a one-line script'

- script: |
    echo 'Java home'
    echo $JAVA_HOME
  displayName: 'JAVA_HOME'

- script: |
    printenv
  displayName: 'printenv'

- script: |
    echo 'WHOAMI'
    whoami
  displayName: 'WHOAMI'

- script: |
    echo $JAVA_HOME_11_X64
  displayName: 'JAVA_HOME_11_X64'