parameters:
- name: 'displayName'
  type: string

steps:
  - task: Gradle@2
    timeoutInMinutes: 4
    displayName: '${{parameters.displayName}}'
    inputs:
      options: --debug
      gradleWrapperFile: 'gradlew'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 'default'
      tasks: 'build'