parameters:
- name: 'displayName'
  type: string

steps:
  - task: Gradle@2
    timeoutInMinutes: 4
    displayName: '${{parameters.displayName}}'
    inputs:
      tasks: 'clean build --info --stacktrace -x test -x integrationTest'
      gradleWrapperFile: 'gradlew'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: 'default'
